name: Isolate
options:
  bundleIdPrefix: com.isolate
  deploymentTarget:
    macOS: "14.0"
targets:
  Isolate:
    type: application
    platform: macOS
    sources: 
      - path: Sources
    info:
      path: Info.plist
      properties:
        CFBundleIdentifier: com.isolate.Isolate
        CFBundleName: Isolate
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.2.8"
        CFBundleVersion: "1.2.8"
        CFBundleIconFile: AppIcon
        LSMinimumSystemVersion: "14.0"
        NSHighResolutionCapable: true
        ATSApplicationFontsPath: "."
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 5.0
        ARCHS: arm64
        ENABLE_HARDENED_RUNTIME: YES
        APP_INTENTS_METADATA_EXTRACTION_ENABLED: NO
        GENERATE_INFOPLIST_FILE: NO
  IsolateTests:
    type: bundle.unit-test
    platform: macOS
    sources: Tests/IsolateTests
    dependencies:
      - target: Isolate
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  IsolateUITests:
    type: bundle.ui-testing
    platform: macOS
    sources: UITests/IsolateUITests
    dependencies:
      - target: Isolate
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
